services:
  web:
    build: ./site1
    ports:
      - "8081:80"
    

  web2:
    build: ./site2
    ports:
      - "8082:80"
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"